# Site settings
title: Atrio
email: hello@atr.io
description: "Atrio Software Solutions (A.S.S.) provides top of the line consulting services in the software industry"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18BBBC #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/users/77131/dorian
  - title: github
    url: https://github.com/dkarter

# Postal address (add as many lines as necessary)
address:
  - line: 605 W Madison St. Unit 3613
  - line: Chicago, IL 60661

# Build settings
markdown: kramdown
permalink: pretty
